### ISSUE TITLE
Can not execute commands inside the container

### ISSUE THREAD

**Issue by DominicWrege** [mbentley/docker-teamspeak#12]
When I'm typing this command I am getting this result:
**sudo docker exec -i -t teamspeak sh /opt/teamspeak/ts3server_startscript.sh status**
Result:
**No server running (ts3server.pid is missing)**

I don't know what I am doing wrong?

**Comment by mbentley** [comment]
The image is utilizing the minimal start script so the full start script doesn't function.

**Comment by DominicWrege** [comment]
So how can I change the admin password for the teamspeak server inside the container?

**Comment by fank** [comment]
Is there a way to change it while running? The only way i know is to use the startup parameter `serveradmin_password`

**Comment by mbentley** [comment]
You have to restart the server (https://support.teamspeakusa.com/index.php?/Knowledgebase/Article/View/326/16/how-do-i-change-or-reset-the-password-of-the-serveradmin-server-query-account).  You can re-create the container and add the `serveradmin_password=password` parameter and it will change the password.  There is no confirmation in the logs of the password change but it works.

So if I started my TS server with:
`docker run -it --rm --name teamspeak -p 9987:9987/udp -p 30033:30033 -p 10011:10011 -p 41144:41144 -v ts-data:/data mbentley/teamspeak`

I would stop the existing container, create a new one:
`docker run -it --rm --name teamspeak -p 9987:9987/udp -p 30033:30033 -p 10011:10011 -p 41144:41144 -v ts-data:/data mbentley/teamspeak serveradmin_password=mynewpassword`

If you're concerned about someone getting the admin password from `docker inspect`, remove the container again and re-create it without the parameter.  The password will still be set.
