### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by byfareska** [mbentley/docker-teamspeak#18]
It is downloading older version than current. It should be 3.1.2, but it is downloading 3.1.1

**Comment by mbentley** [comment]
Hmm odd.  I just built it locally and it installed 3.1.2 but the autobuild on hub was still getting 3.1.1.  I triggered another build so we'll see when that finishes.  Thanks for the heads up.

**Comment by mbentley** [comment]
OK, looks good now:
```
$ docker run -it --rm -e TS3SERVER_LICENSE=accept mbentley/teamspeak help
Found a license agreement method; launching TeamSpeak
2018-04-25 10:37:36.805654|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.1.2 (2018-04-24 06:11:19)
```

**Comment by byfareska** [comment]
it happens again

**Comment by mbentley** [comment]
Sure, so 4 days ago the last time the image was built, 3.1.2 was the latest.  https://forum.teamspeak.com/threads/135623-TeamSpeak-3-server-3-1-3-released

They don't publish a rss feed so I don't have anything to trigger the build at the moment.  I'll see if I can add something that polls the site daily for and update and triggers a build...
