### ISSUE TITLE
Expose new Port 10022

### ISSUE THREAD

**Issue by BenjaminBoehm** [mbentley/docker-teamspeak#19]
Can you please expose the new port (10022) for the ServerQuery via SSH?

see:
https://forum.teamspeak.com/threads/136554-Release-TeamSpeak-3-Server-3-3-0-amp-3-3-1

**Comment by mbentley** [comment]
You can do that today by exposing the port and telling teamspeak to launch with the appropriate parameter:

`-p 10022:10022`
and
`query_protocols=ssh,raw`

So a quick and dirty run without persistent storage would be:
```
docker run -d --name teamspeak \
  -e TS3SERVER_LICENSE=accept \
  -p 9987:9987/udp -p 30033:30033 -p 10011:10011 -p 41144:41144 -p 10022:10022 \
  mbentley/teamspeak \
  query_protocols=ssh,raw
```

I am using the default configuration from the TeamSpeak build but you can definitely override the default config by creating a `ts3server.ini` in your persistent data directory with the additional parameter.

**Comment by mbentley** [comment]
Let me know if there is something else you're looking for besides that.  It's not a feature I use so I am not sure if there is anything else required but it did not look like it to me.
