### ISSUE TITLE
licensekey.dat

### ISSUE THREAD

**Issue by sushi86** [mbentley/docker-teamspeak#2]
Hey, thanks for the container at first!

Any idea how get the ts3 running with a licensekey?

**Comment by mbentley** [comment]
No problem :)  So you should be able to use a volume to get your license key into the `/opt/teamspeak` directory.  I do not have a valid license to test but per the documentation:
"Once the license file is available, copy it into the TeamSpeak 3 Server directory, where the server executable is located."  The executable is in `/opt/teamspeak` so I think that should just work.  So for example, add a volume to make the license file inside the container:

```
docker run -d --restart=always --name teamspeak \
  -p 9987:9987/udp -p 30033:30033 -p 10011:10011 -p 41144:41144 \
  -v /data/teamspeak:/data \
  -v /data/teamspeak/ts3server.sqlitedb:/opt/teamspeak/ts3server.sqlitedb \
  -v /data/licensekey.dat:/opt/teamspeak/licensekey.dat \
  mbentley/teamspeak \
  logpath=/data/logs/ \
  query_ip_whitelist=/data/query_ip_whitelist.txt \
  query_ip_blacklist=/data/query_ip_blacklist.txt
```

If for some reason that does not work, you might want to try to specify where you have it mounted via a volume using the `licensepath` option.  For example:

```
docker run -d --restart=always --name teamspeak \
  -p 9987:9987/udp -p 30033:30033 -p 10011:10011 -p 41144:41144 \
  -v /data/teamspeak:/data \
  -v /data/teamspeak/ts3server.sqlitedb:/opt/teamspeak/ts3server.sqlitedb \
  -v /data/licensekey.dat:/opt/teamspeak/licensekey.dat \
  mbentley/teamspeak \
  logpath=/data/logs/ \
  query_ip_whitelist=/data/query_ip_whitelist.txt \
  query_ip_blacklist=/data/query_ip_blacklist.txt \
  licensepath=/opt/teamspeak/licensekey.dat
```

Let me know if that doesn't work and I'll see what else I can find out.

**Comment by mbentley** [comment]
Actually, if you could let me know if the first option works without specifying the `licenspath` option, that'd be great as I'll update the readme.

**Comment by sushi86** [comment]
Thank you =)

I will try out this evening or tomorrow

**Comment by sushi86** [comment]
Sorry for my late response.

Unfortunately It doesn't work:

`docker run -d --name teamspeak -p 9987:9987/udp -p 30033:30033 -p 10011:10011 -p 41144:41144 mbentley/teamspeak -v /mnt/teamspeak/license/licensekey.dat:/opt/teamspeak/licensekey.dat  licensepath=/opt/teamspeak/licensekey.dat`

Output:

`2016-08-30 11:42:12.269865|WARNING |Accounting    |   |Unable to find valid license key, falling back to limited functionality`

**Comment by fank** [comment]
works fine for me

**Comment by mbentley** [comment]
Thank you for testing @Fank!

**Comment by mbentley** [comment]
@Fank - could you verify that it was the first example that worked fine for you (without specifying `licensepath`)?  I'd assuming that is the case.

**Comment by fank** [comment]
@mbentley i did the same commented above

```
            {
                "Source": "/d/teamspeak/ts3server.sqlitedb",
                "Destination": "/opt/teamspeak/ts3server.sqlitedb",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/d/teamspeak/licensekey.dat",
                "Destination": "/opt/teamspeak/licensekey.dat",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
```
