### ISSUE TITLE
teamspeak 3.8.0

### ISSUE THREAD

**Issue by Horstexplorer** [mbentley/docker-teamspeak#21]
I only get the 3.7.1 release instead of the latest 3.8.0 using the alpine docker. Maybe a rebuild would fix that.

**Comment by mbentley** [comment]
Ah I think the webhooks broke on Docker Hub when I had to reestablish my connection.

**Comment by mbentley** [comment]
Well actually looks like the hackery I was using to get the URL no longer works.  I’ll have to try to fix that when I am in front of a computer.

**Comment by Horstexplorer** [comment]
Thank you,
The command to get the correct version seems to work for me, but it looks like there is no 3.8.0 version available from 4players.de yet, so it may be necessary to switch to https://files.teamspeak-services.com/releases/server/ instead.

**Comment by Horstexplorer** [comment]
Looks like it's working :)
