### ISSUE TITLE
error pulling image configuration: unknown blob

### ISSUE THREAD

**Issue by mkatajah** [mbentley/docker-teamspeak#25]
Getting following error when pulling latest image on fresh new server. OS: Ubuntu 20.04 Docker: latest stable from docker.com.

```
~$ sudo docker pull mbentley/teamspeak
Using default tag: latest
latest: Pulling from mbentley/teamspeak
df20fa9351a1: Pulling fs layer
11c06dca8fe7: Pulling fs layer
80176ed83629: Pulling fs layer
2a3097e3251c: Waiting
error pulling image configuration: unknown blob

~$ sudo docker pull mbentley/teamspeak:latest
latest: Pulling from mbentley/teamspeak
df20fa9351a1: Already exists
11c06dca8fe7: Pulling fs layer
80176ed83629: Pulling fs layer
2a3097e3251c: Pulling fs layer
error pulling image configuration: unknown blob
```

but alpine tag works fine:
```
~$ sudo docker pull mbentley/teamspeak:alpine
alpine: Pulling from mbentley/teamspeak
df20fa9351a1: Pull complete
9e5e1339ce36: Pull complete
896769990208: Pull complete
```
b26263b3b922: Pull complete
Digest: sha256:f6a04944be561ec55edec7f0f63086fe5518febe5fb9873ea4f41154c4e7d9cd
Status: Downloaded newer image for mbentley/teamspeak:alpine
docker.io/mbentley/teamspeak:alpine

**Comment by mbentley** [comment]
Thanks, that's odd.  Something must have gone wrong on the Docker Hub auto-build.  I just triggered a new build on Docker Hub.

**Comment by mkatajah** [comment]
thanks! that seemed to help. :)
