### ISSUE TITLE
Docker not starting after update

### ISSUE THREAD

**Issue by lightlike** [mbentley/docker-teamspeak#26]
**System information**
Linux: Debian
Docker: 5:20.10.2~3-0~debian-buster
Teamspeak: sha256:fd98809baa913dd38aa8ff4b5c4aa38696070b67272aebda9c156361c56dacf0 (latest as of 17.1.2021)

**Logs**
repeats over and over:

```
Found a license agreement method; launching TeamSpeak
/entrypoint.sh: exec: line 39: /usr/bin/tini: not found
```

**Stuff I already did**

- completely recreate image

**Comment by mbentley** [comment]
Whoops, `tini` has a different path in Alpine Linux than Debian.  I'll fix that.

**Comment by mbentley** [comment]
Thanks for the report!  Will be fixed here shortly once the [auto-builds complete on Docker Hub](https://hub.docker.com/repository/docker/mbentley/teamspeak/builds).

**Comment by lightlike** [comment]
Jup. Works nicely.
