### ISSUE TITLE
[Question] Updating

### ISSUE THREAD

**Issue by mrc4tt** [mbentley/docker-teamspeak#38]
Hi.

How can I update the ts3server on docker, without losing (data) files e.g

Shall I just (docker pull) one-time, without worrying about losing data?

**Comment by mbentley** [comment]
So this depends on how you started the container.  Do you have a run command or a compose file?

If we take the example from the README with a persistent data store:

```
docker run -d --restart=always --name teamspeak \
  -e PUID=503 \
  -e PGID=503 \
  -e TS3SERVER_GDPR_SAVE=false \
  -e TS3SERVER_LICENSE=accept \
  -p 9987:9987/udp -p 30033:30033 -p 10011:10011 -p 41144:41144 \
  -v /data/teamspeak:/data \
  mbentley/teamspeak
```

You would pull a new image, stop the container, and then remove the container:

```
docker pull mbentley/teamspeak
docker stop -t 15 teamspeak
docker rm teamspeak
```

And then re-create the container with the exact same run command as originally ran which will bind mount the persistent data to the appropriate location.

If you don't know how your persistent data is saved, run the following and provide the output (sanitizing any passwords or other data):

```
docker inspect <container-name>
```

**Comment by mrc4tt** [comment]
Hi @mbentley,

I'm running A bash script (when I creating, which is easier for me since they will (restart: always if the server rebooting)
https://pastebin.com/MYVjzRD5

It saves its own data from each server/folder.
Example: 
```
root@vps-53f8ea12:~/srvs/ts3/mrc4t# ls
data  docker-compose.yml
root@vps-53f8ea12:~/srvs/ts3/mrc4t/data# ls
files  logs  ts3server.ini  ts3server.sqlitedb  ts3server.sqlitedb-shm  ts3server.sqlitedb-wal
```

So I need to pull and stop them all. Or can I just pull, and just restart them all?

**Comment by mbentley** [comment]
Yeah, you'll need to pull the image and recreate the containers.  Just restarting the containers will not update the image.

**Comment by mbentley** [comment]
Let me know if you have any other issues updating.

**Comment by mrc4tt** [comment]
Hey @mbentley 
It worked with the pulled image!
I have a question:

I'm using this docker-compose. Will you recommend I use "network_mode" as a bridge instead, of creating (their network per TS3 server)?

daemon.json with this:
`"bip": "172.26.0.1/16"`

Example of how it looks with 3 TS Servers (Separate)
A > without network_mode: bridge =>172.22.0.0 (br-033cf57bd843)
B > with network_mode: bridge => 172.26.0.0 (docker0)
C > without network_mode: bridge => 172.23.0.0 (br-f251413cbdd0)

**What can you recommend to me here?**

**Comment by mbentley** [comment]
Just depends on your use case.  Using the default bridge, the containers will be isolated from each other, unable to communicate.  If you're only putting the containers on their own network, you're not doing anything besides adding bridges for no real benefit, in my opinion.  The docker docs go over the differences between the default bridge network and user defined bridges:  https://docs.docker.com/network/bridge/  If you're not using any of the features of a user defined bridge network, it's probably fine to just use the default bridge.

**Comment by mrc4tt** [comment]
So I can just leave it as default, to use docker0's IP. Without any problems, otherwise, I can always change it around.
