### ISSUE TITLE
Problem - The default license has expired, Teamspeak not updating

### ISSUE THREAD

**Issue by Setsumia** [mbentley/docker-teamspeak#39]
Hello.
I have been using arm32v7-latest-box86-predownloaded container to be more specific for the last 4 month without problem but today no one could enter the server so I restarted the container and after 5 seconds it goes down with this log.

![image](https://user-images.githubusercontent.com/117130822/199136878-02a5a0a9-df5d-442e-bd9b-e688f601133b.png)

My TeamSpeak server is on version 3.13.6 and I read the changelog for version 3.13.7 fixes this "New embedded default license is valid until the 1st of July 2027"

Is there a way to update the server or is a new compose version in need to be released?
Thank you.

**Comment by mbentley** [comment]
Hmm, the container that you're mentioning is running the s6 process supervisor so the image that you have been running isn't this one.  I can't say for certain what would be the right move if you wanted to migrate to my image but normally, I would expect to be able to pull a newer version of the image you're using and re-create the container and then it should be up to date.

**Comment by Setsumia** [comment]
You are right, I was using another image but after some trial and error I was able to re-create the container and update. Thank you.
