### ISSUE TITLE
Icons are not stored

### ISSUE THREAD

**Issue by Vild** [mbentley/docker-teamspeak#6]
Hey, I just noticed now that all my icons disappeared when I restarted the container.
This was because the icon folder wasn't binded to a folder outside the container.
The folder where teamspeak stores the icons is in `/opt/teamspeak/files/virtualserver_1/internal/icons`.

I would recommend that `-v /srv/teamspeak/icons:/opt/teamspeak/files/virtualserver_1/internal/icons` or something similar is added to the example command.

**Comment by mbentley** [comment]
Thanks!  Updated the docs to reflect using a volume to persist `/opt/teamspeak/files` from inside the container.
